### ISSUE TITLE
IP Address

### ISSUE THREAD

**Issue by kayatopluluk** [TlatoaniHJ/WebSKT#1]
Create server skript code:
```JavaScript
websocket server "localhost":
  on open:
    event-request-ip-adress??
```

How can I access the IP addresses of the people who connect to the server?

**Comment by TlatoaniHJ** [comment]
`remote host` gives the hostname of the client, which is usually the IP address.

**Comment by TlatoaniHJ** [comment]
Note that questions like these aren't really appropriate as issues, it would be better if you could ask in the Discord or on the skUnity forums. If you have more questions please ask there.
